### ISSUE TITLE
请问下您的弹幕自定义解析器？

### ISSUE THREAD

**Issue by marren06** [alexwan02/DFMSample#1]
![image](https://cloud.githubusercontent.com/assets/17778482/21711461/2de474c4-d42a-11e6-977b-e0a12e9000f5.png)
我使用你的自定义解析器加载接口怎么报出这个错？
![image](https://cloud.githubusercontent.com/assets/17778482/21711487/4061f702-d42a-11e6-999f-a7a55e6b749b.png)
期待大神指点迷津！

**Comment by alexwan02** [comment]
Generally speaking, ```java.net.MalformedURLException: Protocol not found``` exception because
the Uri that you given is not the correct Uri object .

**Comment by marren06** [comment]
大神，昨天问你的自定义解析器的问题，我现在要网络请求接口获取弹幕内容，你写的自定义解析器是要把弹幕内容转化成      流     的形式进行解析吗？
![image](https://cloud.githubusercontent.com/assets/17778482/21739847/1e122754-d4e2-11e6-9138-140e0ccf4434.png)

![image](https://cloud.githubusercontent.com/assets/17778482/21739869/bfc7c284-d4e2-11e6-9691-1c011dce8078.png)

你的这个加载弹幕的方式最终还是转换成流的形式啊  不是直接加载  直接就能加载接口地址  是吗？

**Comment by alexwan02** [comment]
@xuekaiqi  是的。如果自定义的话最后处理都是使用流方式，`Danmaku`定义的也是最终转换为流的方式。
